USE DBMS;

CREATE TABLE STUDENT (
    NAME VARCHAR(30) NOT NULL,
    STUDENT_NUMBER INT NOT NULL PRIMARY KEY,
    CLASS INT NOT NULL,
    MAJOR VARCHAR(30) NOT NULL
);


CREATE TABLE COURSE (
    COURSE_NAME VARCHAR(30) NOT NULL,
    COURSE_NUMBER VARCHAR(10) PRIMARY KEY,
    CREDIT_HOURS INT NOT NULL,
    DEPARTMENT VARCHAR(30) NOT NULL
);

CREATE TABLE PREREQUISITE (
    COURSE_NUMBER VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES COURSE(COURSE_NUMBER),
    PREREQUISITE_NUMBER VARCHAR(10) NOT NULL PRIMARY KEY
);

CREATE TABLE SECTION (
    SECTION_IDENTIFIER INT NOT NULL PRIMARY KEY,
    COURSE_NUMBER VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES COURSE(COURSE_NUMBER),
    SEMESTER VARCHAR(30) NOT NULL,
    YEAR INT NOT NULL,
    INSTRUCTOR VARCHAR(20) NOT NULL
);

CREATE TABLE GRADE_REPORT (
    STUDENT_NUMBER INT NOT NULL FOREIGN KEY REFERENCES STUDENT(STUDENT_NUMBER),
    SECTION_IDENTIFIER INT NOT NULL FOREIGN KEY REFERENCES SECTION(SECTION_IDENTIFIER),
    GRADE VARCHAR(1) NOT NULL,
    PRIMARY KEY(STUDENT_NUMBER,SECTION_IDENTIFIER)
);

INSERT INTO STUDENT VALUES 
    ('Smith',17,1,'CS'),
    ('Brown',8,2,'CS');

INSERT INTO COURSE VALUES
    ('Intro to Computer Science','CS1310',4,'CS'),
    ('Data Structures','CS3320',3,'CS'),
    ('Discrete Mathematics','MATH2410',3,'MATH'),
    ('Database','CS3380',3,'CS');

INSERT INTO SECTION VALUES
    (85,'MATH2410','Fall',07,'King'),
    (92,'CS1310','Fall',07,'Anderson'),
    (102,'CS3320','Spring',08,'Knuth'),
    (112,'MATH2410','Fall',08,'Chang'),
    (119,'CS1310','Fall',08,'Anderson'),
    (135,'CS3380','Fall',08,'Stone');

INSERT INTO PREREQUISITE VALUES
    ('CS3380','CS3320'),
    ('CS3380','MATH2410'),
    ('CS3320','CS1310');

INSERT INTO GRADE_REPORT VALUES
    (17,112,'B'),
    (17,119,'C'),
    (8,85,'A'),
    (8,92,'A'),
    (8,102,'B'),
    (8,135,'A');

SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM PREREQUISITE;
SELECT * FROM SECTION;
SELECT * FROM GRADE_REPORT;

/* 
DROP TABLE GRADE_REPORT,SECTION,PREREQUISITE,COURSE,STUDENT;
*/